#pragma once


#define JMCPP_VERSION_MAJOR 1
#define JMCPP_VERSION_MINOR 2
#define JMCPP_VERSION_PATCH 0
#define JMCPP_VERSION_STR "1.2.0"
#define JMCPP_VERSION ((JMCPP_VERSION_MAJOR<<16)|(JMCPP_VERSION_MINOR<<8)|(JMCPP_VERSION_PATCH))

